# Generated by Django 2.2.1 on 2019-05-29 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='fotos/')),
                ('nome', models.CharField(max_length=120)),
                ('altura', models.FloatField()),
                ('ponto_saude', models.PositiveIntegerField()),
                ('ataque', models.PositiveIntegerField()),
                ('defesa', models.PositiveIntegerField()),
                ('ataque_especial', models.PositiveIntegerField()),
                ('defesa_especial', models.PositiveIntegerField()),
                ('velocidade', models.PositiveIntegerField()),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Categoria')),
                ('fk_habilidades', models.ManyToManyField(to='pokedex.Habilidade')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='fk_evolucao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pokedex.Evolucao'),
            preserve_default=False,
        ),
    ]
