# Generated by Django 2.2.1 on 2019-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20190528_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='fk_evolucao',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolucao',
            field=models.ManyToManyField(to='pokedex.Pokemon'),
        ),
    ]
