# Generated by Django 2.2.1 on 2019-05-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20190530_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolucao',
            field=models.ManyToManyField(blank=True, null=True, to='pokedex.Pokemon'),
        ),
    ]
