# Generated by Django 2.2.1 on 2019-05-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20190530_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evolucao',
        ),
    ]
